name-template: "v$NEXT_PATCH_VERSION 🌈"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 新功能"
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: "🐛 修复"
    labels:
      - "bug"
      - "fix"
      - "bugfix"
  - title: '📚 文档更新'
    labels:
      - 'docs'
  - title: '🎨 代码样式'
    labels:
      - 'style'
  - title: '🔄 代码重构'
    labels:
      - 'refactor'
  - title: '⚡ 性能优化'
    labels:
      - 'perf'
  - title: '🧪 测试'
    labels:
      - 'test'
  - title: "🧰 维护和工具"
    labels:
      - "chore"
      - "maintenance"
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\[`*_{}'
version-resolver:
  major:
    labels:
      - "major"
      - 'breaking-change'
  minor:
    labels:
      - "minor"
      - 'feat'
  patch:
    labels:
      - "patch"
      - 'fix'

  default: patch

header: |
  # 🎉 新版本发布

  很高兴向您介绍此版本中的更新内容。感谢您一如既往的支持！
  如果您对本次更新有任何问题，或希望提供反馈， 请在[GitHub Issues](https://github.com/h-yw/mp-editor/issues) 中提交问题。

  ---
footer: |
  ---
  ## ❓ 常见问题

  如果您在使用过程中遇到问题，请参考以下资源：
  
  - [提交 Issue](https://github.com/h-yw/mp-editor/issues)

  再次感谢您对我们项目的支持！

template: |
  ## 变更内容

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION