# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mp eeditor ci

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: set node V20.15.1
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.1

    - name: run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: build production
      uses: borales/actions-yarn@v4
      with: 
        cmd: build
        
    - name: 📦 Create Release
      uses: simbo/action-semver-release-action@latest
    
