# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mp editor ci

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: enable corepack
        run: corepack enable

      - name: set node V20.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
          cache: yarn

      - name: Install latest yarn
        run: corepack prepare yarn@stable --activate

      - name: activate latest yarm
        run: yarn set version stable

      - name: install dep
        run: yarn install

      - name: build production
        run: yarn build

      - name: Zip build files
        run: |
          zip -r mp-editor.zip ./dist

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: mp-editor
          path: mp-editor.zip
  draft-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build result
        uses: actions/download-artifact@v3
        with:
          name: mp-editor

      - name: Draft Release
        id: draft_release
        uses: release-drafter/release-drafter@v6.0.0
        with:
          config-name: workflows/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to Draft Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: mp-editor.zip
          asset_name: mp-editor.zip
          asset_content_type: application/zip
