# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mp editor ci

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: enable corepack
      run: corepack enable
      
    - name: set node V20.15.1
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.1
        cache: yarn

    - name:  Install latest yarn
      run: corepack prepare yarn@stable --activate

    - name: activate latest yarm
      run: yarn set version stable

    - name: install dep
      run: yarn install 
      
    - name: build production
      run: yarn build
        
    - name: 📦 Create Release
      uses: simbo/action-semver-release-action@latest
    
